import { useState, useEffect } from 'react';
import { useAuth } from '../../context/AuthContext';
import { getNextSundayLocalDate } from '../../utils/calendarUtils';
import { getShoppingList, syncShoppingList, checkShoppingListItem } from '../../api/apiClient';
import './ShoppingList.css';

export default function ShoppingList() {
  const { user } = useAuth();
  const userId = user?.id || user?._id;

  const [shoppingItems, setShoppingItems] = useState([]);
  const [hasPlan, setHasPlan] = useState(false);
  const [loading, setLoading] = useState(false);
  const [syncing, setSyncing] = useState(false);
  const [weekStartDate, setWeekStartDate] = useState(getNextSundayLocalDate());
  const [message, setMessage] = useState({ text: '', type: '' });

  // Fetch the shopping list
  const fetchShoppingListData = async (showLoading = true) => {
    if (!userId || !weekStartDate) return;
    if (showLoading) setLoading(true);
    try {
      const res = await getShoppingList(userId, weekStartDate);
      setShoppingItems(res.shopping_list || []);
      setHasPlan(res.has_plan);
    } catch (err) {
      console.error("Failed to load shopping list:", err);
      showMessage("Failed to load shopping list.", "error");
    } finally {
      if (showLoading) setLoading(false);
    }
  };

  useEffect(() => {
    fetchShoppingListData();
  }, [userId, weekStartDate]);

  const showMessage = (text, type = 'success') => {
    setMessage({ text, type });
    setTimeout(() => setMessage({ text: '', type: '' }), 4000);
  };

  const handleSyncList = async () => {
    if (!userId || !weekStartDate) return;
    setSyncing(true);
    try {
      const res = await syncShoppingList(userId, weekStartDate);
      setShoppingItems(res.shopping_list || []);
      showMessage("Shopping list successfully synced with your pantry and menu!", "success");
    } catch (err) {
      console.error("Failed to sync shopping list:", err);
      showMessage("AI Sync failed. Please verify you have a saved weekly plan.", "error");
    } finally {
      setSyncing(false);
    }
  };

  const handleToggleCheckItem = async (item) => {
    if (!userId || !weekStartDate) return;
    // Optimistic UI update
    setShoppingItems(prev => prev.filter(i => i !== item));
    
    try {
      const res = await checkShoppingListItem(userId, weekStartDate, item, true);
      setShoppingItems(res.shopping_list || []);
      showMessage(`"${item}" purchased and added to your Pantry inventory!`, "success");
    } catch (err) {
      console.error("Failed to check item:", err);
      showMessage("Failed to check off item.", "error");
      // Revert if error
      fetchShoppingListData(false);
    }
  };

  return (
    <div className="shopping-page-container">
      <div className="shopping-header-section">
        <h1>Weekly Shopping List</h1>
        <p>Your automatic grocery checklist generated by comparing the weekly meal plan against what is already in your pantry.</p>
      </div>

      {message.text && (
        <div className={`shopping-toast ${message.type}`}>
          {message.text}
        </div>
      )}

      <div className="shopping-controls">
        <div className="week-selector-card">
          <label>Target Week (Starts Sunday):</label>
          <input
            type="date"
            value={weekStartDate}
            onChange={(e) => setWeekStartDate(e.target.value)}
            className="week-date-input"
          />
        </div>

        {hasPlan && (
          <button
            type="button"
            className="sync-btn"
            onClick={handleSyncList}
            disabled={syncing}
          >
            {syncing ? (
              <>
                <span className="mini-spinner"></span>
                Generating missing items...
              </>
            ) : (
              "Sync with Pantry & Menu (AI)"
            )}
          </button>
        )}
      </div>

      {loading ? (
        <div className="shopping-loading-container">
          <div className="shopping-spinner"></div>
          <p>Loading your shopping list...</p>
        </div>
      ) : (
        <div className="shopping-card-panel">
          {!hasPlan ? (
            <div className="no-plan-state">
              <div className="no-plan-icon">📋</div>
              <h3>No Weekly Plan Saved</h3>
              <p>You haven't saved a meal plan for the week of {weekStartDate} yet. Go to the Planner page to design and save a menu, and your shopping list will be generated automatically!</p>
            </div>
          ) : shoppingItems.length === 0 ? (
            <div className="all-bought-state">
              <div className="all-bought-icon">🎉</div>
              <h3>You are fully stocked!</h3>
              <p>All ingredients needed for your weekly meals are already present in your Pantry, or you have checked off all items. Happy cooking!</p>
            </div>
          ) : (
            <div className="shopping-checklist-container">
              <h2>Items to Buy ({shoppingItems.length})</h2>
              <p className="checklist-subtitle">Checking off an item removes it from this list and automatically adds it to your Pantry.</p>
              
              <div className="shopping-items-list">
                {shoppingItems.map((item) => (
                  <div key={item} className="shopping-item-row" onClick={() => handleToggleCheckItem(item)}>
                    <div className="checkbox-container">
                      <span className="checkbox-custom"></span>
                    </div>
                    <span className="shopping-item-name">{item}</span>
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>
      )}
    </div>
  );
}
